"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { supabaseBrowser } from "../lib/supabase";

type Settlement = { platform: string; settlement_date: string | null; net_deposit_amount: number | null; status: string };
const yen=(n:number)=>`¥${Math.round(n).toLocaleString()}`;

export default function ManagementSnapshot(){
 const [target,setTarget]=useState<HTMLElement|null>(null); const [data,setData]=useState<{sales:number;gross:number;marketplace:number;general:number;profit:number;deposits:number;rows:Settlement[]}>({sales:0,gross:0,marketplace:0,general:0,profit:0,deposits:0,rows:[]});
 useEffect(()=>{const find=()=>{const headings=Array.from(document.querySelectorAll("h2"));const h=headings.find(x=>(x.textContent||"").replace(/\s/g,"")==="今月の売上履歴");const section=h?.closest("section") as HTMLElement|null;if(section){let el=document.getElementById("management-snapshot-slot");if(!el){el=document.createElement("div");el.id="management-snapshot-slot";section.parentElement?.insertBefore(el,section);}setTarget(el);return true;}return false;};find();const timer=window.setInterval(find,700);return()=>window.clearInterval(timer);},[]);
 useEffect(()=>{let cancelled=false;async function load(){const supabase=supabaseBrowser;const now=new Date();const y=now.getFullYear();const m=String(now.getMonth()+1).padStart(2,"0");const start=`${y}-${m}-01`;const end=new Date(y,now.getMonth()+1,0).toISOString().slice(0,10);const [sales,costs,expenses,settlements]=await Promise.all([supabase.from("sales_history").select("total_sales,total_cost,shipping_cost").eq("is_cancelled",false).gte("sale_date",start).lte("sale_date",end),supabase.from("marketplace_cost_entries").select("amount").gte("expense_month",start).lte("expense_month",end),supabase.from("expense_entries").select("amount").gte("entry_date",start).lte("entry_date",end),supabase.from("marketplace_settlements").select("platform,settlement_date,net_deposit_amount,status").gte("settlement_date",start).order("settlement_date",{ascending:true}).limit(30)]);if(cancelled)return;const salesRows=sales.data||[];const salesTotal=salesRows.reduce((s,r)=>s+Number(r.total_sales||0),0);const gross=salesRows.reduce((s,r)=>s+Number(r.total_sales||0)-Number(r.total_cost||0)-Number(r.shipping_cost||0),0);const marketplace=(costs.data||[]).reduce((s,r)=>s+Number(r.amount||0),0);const general=(expenses.data||[]).reduce((s,r)=>s+Number(r.amount||0),0);const rows=(settlements.data||[]) as Settlement[];const deposits=rows.reduce((s,r)=>s+Number(r.net_deposit_amount||0),0);setData({sales:salesTotal,gross,marketplace,general,profit:gross-marketplace-general,deposits,rows});}load();return()=>{cancelled=true;};},[]);
 if(!target)return null;return createPortal(<section style={{marginBottom:20,background:"#fff",border:"1px solid #e5e7eb",borderRadius:16,padding:18,boxShadow:"0 4px 14px rgba(17,24,39,.04)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div style={{fontSize:12,letterSpacing:1.5,color:"#6b7280",fontWeight:800}}>MANAGEMENT SNAPSHOT</div><h2 style={{margin:"3px 0 0",fontSize:22}}>今月の経営状況・確定入金予定</h2></div><div style={{fontSize:12,color:"#6b7280"}}>※ 入金予定は登録済みPDFベース</div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:14}}><div style={{padding:14,borderRadius:12,background:"#f8fafc"}}><div style={{color:"#6b7280",fontSize:12}}>今月売上</div><strong style={{fontSize:22}}>{yen(data.sales)}</strong></div><div style={{padding:14,borderRadius:12,background:"#f8fafc"}}><div style={{color:"#6b7280",fontSize:12}}>今月粗利</div><strong style={{fontSize:22,color:data.gross>=0?"#15803d":"#dc2626"}}>{yen(data.gross)}</strong></div><div style={{padding:14,borderRadius:12,background:"#f8fafc"}}><div style={{color:"#6b7280",fontSize:12}}>モール＋一般経費</div><strong style={{fontSize:22}}>{yen(data.marketplace+data.general)}</strong></div><div style={{padding:14,borderRadius:12,background:"#ecfdf5"}}><div style={{color:"#166534",fontSize:12}}>簡易利益</div><strong style={{fontSize:22,color:data.profit>=0?"#15803d":"#dc2626"}}>{yen(data.profit)}</strong></div><div style={{padding:14,borderRadius:12,background:"#eff6ff"}}><div style={{color:"#1d4ed8",fontSize:12}}>今後の確定入金予定</div><strong style={{fontSize:22,color:"#1d4ed8"}}>{yen(data.deposits)}</strong></div></div><div style={{marginTop:14,display:"flex",gap:8,flexWrap:"wrap"}}>{data.rows.slice(0,6).map((r,i)=><div key={`${r.platform}-${r.settlement_date}-${i}`} style={{padding:"8px 11px",border:"1px solid #dbeafe",borderRadius:10,background:"#f8fbff",fontSize:13}}><b>{r.platform}</b>　{r.settlement_date||"—"}　<strong>{yen(Number(r.net_deposit_amount||0))}</strong></div>)}</div></section>,target);
}
