"use client";

import { useEffect, useMemo, useRef, useState, type ChangeEvent, type CSSProperties, type ReactNode } from "react";
import { supabaseBrowser } from "../lib/supabase";

type Product={id:string;name:string;jan_code?:string|null;sku?:string|null;model_number?:string|null;brand?:string|null;category?:string|null;stock_quantity?:number|null;reorder_point?:number|null;cost_price?:number|null;selling_price?:number|null;created_at?:string|null};
type Sale={id:string;product_id:string;sale_date:string;sales_channel?:string|null;quantity?:number|null;total_sales?:number|null;total_cost?:number|null;gross_profit?:number|null;shipping_cost?:number|null;is_cancelled?:boolean};
type Purchase={id:string;product_id:string;purchase_date:string;supplier?:string|null;quantity?:number|null;total_cost?:number|null};
type Expense={id:string;entry_date:string;category:string;description:string;amount?:number|null};

const today=new Date().toISOString().slice(0,10), thisMonth=today.slice(0,7);
const yen=(n:number|null|undefined)=>`¥${Math.round(Number(n||0)).toLocaleString()}`;
const mon=(d:string)=>d.slice(0,7), yr=(d:string)=>d.slice(0,4);
const cell=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;
const card:CSSProperties={background:"#fff",border:"1px solid #e5e7eb",borderRadius:16,padding:20,boxShadow:"0 2px 8px rgba(0,0,0,.04)"};
const btn:CSSProperties={border:0,borderRadius:10,padding:"10px 14px",fontWeight:700,cursor:"pointer"};

function parseCsv(t:string){const out:string[][]=[];let r:string[]=[],c="",q=false;for(let i=0;i<t.length;i++){const x=t[i];if(x==='"'){if(q&&t[i+1]==='"'){c+='"';i++;}else q=!q;}else if(x===','&&!q){r.push(c);c="";}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&t[i+1]==='\n')i++;r.push(c);c="";if(r.some(v=>v.trim()))out.push(r);r=[];}else c+=x;}if(c||r.length){r.push(c);if(r.some(v=>v.trim()))out.push(r);}return out;}
function download(name:string,text:string,type="text/plain;charset=utf-8"){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}

export default function Management(){
 const sb=supabaseBrowser;const [products,setProducts]=useState<Product[]>([]),[sales,setSales]=useState<Sale[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[expenses,setExpenses]=useState<Expense[]>([]);const [loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[tab,setTab]=useState("overview"),[selectedMonth,setSelectedMonth]=useState(thisMonth),[filter,setFilter]=useState(""),[importing,setImporting]=useState(false);const file=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);const [p,s,pu,e]=await Promise.all([sb.from("products").select("id,name,jan_code,sku,model_number,brand,category,stock_quantity,reorder_point,cost_price,selling_price,created_at").limit(10000),sb.from("sales_history").select("id,product_id,sale_date,sales_channel,quantity,total_sales,total_cost,gross_profit,shipping_cost,is_cancelled").order("sale_date",{ascending:false}).limit(10000),sb.from("purchase_history").select("id,product_id,purchase_date,supplier,quantity,total_cost").order("purchase_date",{ascending:false}).limit(10000),sb.from("expense_entries").select("id,entry_date,category,description,amount").order("entry_date",{ascending:false}).limit(10000)]);const er=[p.error,s.error,pu.error,e.error].find(Boolean);if(er)setMsg(`読み込みエラー：${er.message}`);setProducts((p.data||[]) as Product[]);setSales((s.data||[]) as Sale[]);setPurchases((pu.data||[]) as Purchase[]);setExpenses((e.data||[]) as Expense[]);setLoading(false);}
 useEffect(()=>{load()},[]);
 const active=useMemo(()=>sales.filter(x=>!x.is_cancelled),[sales]);const pm=useMemo(()=>Object.fromEntries(products.map(p=>[p.id,p])),[products]);
 const months=useMemo(()=>Array.from(new Set([thisMonth,...sales.map(x=>mon(x.sale_date)),...purchases.map(x=>mon(x.purchase_date)),...expenses.map(x=>mon(x.entry_date))])).sort().reverse(),[sales,purchases,expenses]);const year=yr(selectedMonth);
 const ms=useMemo(()=>active.filter(x=>mon(x.sale_date)===selectedMonth),[active,selectedMonth]);const mp=useMemo(()=>purchases.filter(x=>mon(x.purchase_date)===selectedMonth),[purchases,selectedMonth]);const me=useMemo(()=>expenses.filter(x=>mon(x.entry_date)===selectedMonth),[expenses,selectedMonth]);
 const sum=(a:number[],b:number)=>a.reduce((x,y)=>x+y,b);const salesTotal=sum(ms.map(x=>Number(x.total_sales||0)),0),costTotal=sum(ms.map(x=>Number(x.total_cost||0)),0),shipTotal=sum(ms.map(x=>Number(x.shipping_cost||0)),0),gross=sum(ms.map(x=>Number(x.gross_profit||0)),0),expenseTotal=sum(me.map(x=>Number(x.amount||0)),0),purchaseTotal=sum(mp.map(x=>Number(x.total_cost||0)),0),operating=gross-expenseTotal,stockUnits=sum(products.map(x=>Number(x.stock_quantity||0)),0),stockValue=sum(products.map(x=>Number(x.stock_quantity||0)*Number(x.cost_price||0)),0);
 const productRows=useMemo(()=>{const m:Record<string,{sales:number;cost:number;ship:number;profit:number;qty:number}>={};active.forEach(s=>{m[s.product_id]??={sales:0,cost:0,ship:0,profit:0,qty:0};m[s.product_id].sales+=Number(s.total_sales||0);m[s.product_id].cost+=Number(s.total_cost||0);m[s.product_id].ship+=Number(s.shipping_cost||0);m[s.product_id].profit+=Number(s.gross_profit||0);m[s.product_id].qty+=Number(s.quantity||0)});const k=filter.trim().toLowerCase();return products.map(p=>{const v=m[p.id]||{sales:0,cost:0,ship:0,profit:0,qty:0};return {...p,...v,margin:v.sales?v.profit/v.sales*100:0}}).filter(p=>!k||[p.name,p.jan_code,p.sku,p.model_number,p.brand].some(v=>String(v||"").toLowerCase().includes(k))).sort((a,b)=>b.profit-a.profit)},[products,active,filter]);
 const channelRows=useMemo(()=>{const m:Record<string,{sales:number;cost:number;ship:number;profit:number;qty:number}>={};ms.forEach(s=>{const k=s.sales_channel||"その他";m[k]??={sales:0,cost:0,ship:0,profit:0,qty:0};m[k].sales+=Number(s.total_sales||0);m[k].cost+=Number(s.total_cost||0);m[k].ship+=Number(s.shipping_cost||0);m[k].profit+=Number(s.gross_profit||0);m[k].qty+=Number(s.quantity||0)});return Object.entries(m).map(([channel,v])=>({channel,...v,margin:v.sales?v.profit/v.sales*100:0})).sort((a,b)=>b.profit-a.profit)},[ms]);
 const lastSale=useMemo(()=>{const m:Record<string,string>={};active.forEach(s=>{if(!m[s.product_id]||s.sale_date>m[s.product_id])m[s.product_id]=s.sale_date});return m},[active]);
 const aging=useMemo(()=>products.filter(p=>Number(p.stock_quantity||0)>0).map(p=>{const d=lastSale[p.id]||(p.created_at?p.created_at.slice(0,10):today);const days=Math.max(0,Math.floor((new Date(today).getTime()-new Date(d).getTime())/86400000));return {p,days,last:lastSale[p.id]||null,value:Number(p.stock_quantity||0)*Number(p.cost_price||0)}}).sort((a,b)=>b.days-a.days),[products,lastSale]);
 const reorder=useMemo(()=>products.filter(p=>Number(p.stock_quantity||0)<=Number(p.reorder_point||0)).sort((a,b)=>Number(a.stock_quantity||0)-Number(b.stock_quantity||0)),[products]);
 const annual=useMemo(()=>Array.from({length:12},(_,i)=>{const m=`${year}-${String(i+1).padStart(2,"0")}`,s=active.filter(x=>mon(x.sale_date)===m),p=purchases.filter(x=>mon(x.purchase_date)===m),e=expenses.filter(x=>mon(x.entry_date)===m);const sales=sum(s.map(x=>Number(x.total_sales||0)),0),cost=sum(s.map(x=>Number(x.total_cost||0)),0),ship=sum(s.map(x=>Number(x.shipping_cost||0)),0),gross=sum(s.map(x=>Number(x.gross_profit||0)),0),expense=sum(e.map(x=>Number(x.amount||0)),0),purchase=sum(p.map(x=>Number(x.total_cost||0)),0);return{m,sales,cost,ship,gross,expense,operating:gross-expense,purchase,cash:sales-purchase-expense}}),[active,purchases,expenses,year]);
 const at=annual.reduce((a,r)=>({sales:a.sales+r.sales,cost:a.cost+r.cost,ship:a.ship+r.ship,gross:a.gross+r.gross,expense:a.expense+r.expense,operating:a.operating+r.operating,purchase:a.purchase+r.purchase,cash:a.cash+r.cash}),{sales:0,cost:0,ship:0,gross:0,expense:0,operating:0,purchase:0,cash:0});
 function ledgerCsv(){const rows:unknown[][]=[["日付","区分","内容","相手先","売上","原価/仕入","送料","経費","利益"]];ms.forEach(x=>rows.push([x.sale_date,"売上",pm[x.product_id]?.name||"商品不明",x.sales_channel||"",x.total_sales||0,x.total_cost||0,x.shipping_cost||0,0,x.gross_profit||0]));mp.forEach(x=>rows.push([x.purchase_date,"仕入",pm[x.product_id]?.name||"商品不明","",0,x.total_cost||0,0,0,0]));me.forEach(x=>rows.push([x.entry_date,x.category,x.description,"",0,0,0,x.amount||0,-Number(x.amount||0)]));download(`帳簿_${selectedMonth}.csv`,`\uFEFF${rows.map(r=>r.map(cell).join(",")).join("\n")}`,"text/csv;charset=utf-8")}
 function backup(){download(`経営システム_バックアップ_${today}.json`,JSON.stringify({exported_at:new Date().toISOString(),products,sales,purchases,expenses},null,2),"application/json;charset=utf-8")}
 function productsCsv(){const rows=["商品名,JANコード,SKU,型番,ブランド,カテゴリ,在庫数,発注点,原価,販売価格".split(","),...products.map(p=>[p.name,p.jan_code,p.sku,p.model_number,p.brand,p.category,p.stock_quantity,p.reorder_point,p.cost_price,p.selling_price])];download(`商品マスター_${today}.csv`,`\uFEFF${rows.map(r=>r.map(cell).join(",")).join("\n")}`,"text/csv;charset=utf-8")}
 async function importCsv(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setImporting(true);setMsg("");try{const rows=parseCsv(await f.text());if(rows.length<2)throw new Error("CSVにデータがありません");const h=rows[0].map(x=>x.trim().toLowerCase());const ix=(...n:string[])=>n.map(x=>h.indexOf(x)).find(x=>x>=0)??-1;const ni=ix("商品名","name"),ji=ix("janコード","jan_code","jan"),si=ix("sku"),mi=ix("型番","model_number"),bi=ix("ブランド","brand"),ci=ix("カテゴリ","category"),qi=ix("在庫数","stock_quantity","stock"),ri=ix("発注点","reorder_point"),co=ix("原価","cost_price","仕入単価"),sp=ix("販売価格","selling_price","売価");if(ni<0)throw new Error("商品名列が必要です");let add=0,upd=0;for(const r of rows.slice(1)){const v=(i:number)=>i>=0?(r[i]||"").trim():"";const name=v(ni);if(!name)continue;const jan=v(ji)||null;const payload={name,jan_code:jan,sku:v(si)||null,model_number:v(mi)||null,brand:v(bi)||null,category:v(ci)||null,stock_quantity:Number(v(qi)||0),reorder_point:Number(v(ri)||0),cost_price:Number(v(co)||0),selling_price:Number(v(sp)||0)};let id:string|null=null;if(jan){const q=await sb.from("products").select("id").eq("jan_code",jan).maybeSingle();id=q.data?.id||null}const r2=id?await sb.from("products").update(payload).eq("id",id):await sb.from("products").insert(payload);if(r2.error)throw r2.error;id?upd++:add++}setMsg(`CSV取込完了：新規${add}件 / 更新${upd}件`);await load()}catch(e:any){setMsg(`CSV取込エラー：${e?.message||"失敗しました"}`)}finally{setImporting(false);if(file.current)file.current.value=""}}
 const tabs:[string,string][]=[["overview","🏠 経営全体"],["products","💰 商品別利益"],["channels","🛒 販売先別"],["stock","📦 在庫分析"],["purchases","🧾 仕入・発注"],["pl","📊 月次・年次"],["cash","💴 資金繰り"],["io","📥 CSV・バックアップ"]];
 if(loading)return <main style={{padding:40,fontFamily:"system-ui"}}>経営システムを読み込んでいます…</main>;
 const table=(heads:string[],rows:ReactNode[])=> <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760}}><thead><tr>{heads.map(h=><th key={h} style={{textAlign:h==="商品"||h==="販売先"||h==="月"?"left":"right",padding:9,borderBottom:"2px solid #e5e7eb"}}>{h}</th>)}</tr></thead><tbody>{rows}</tbody></table></div>;
 return <main style={{minHeight:"100vh",background:"#f5f7fb",padding:"28px 18px 70px",color:"#111827",fontFamily:"system-ui,-apple-system,BlinkMacSystemFont,sans-serif"}}><div style={{maxWidth:1400,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,flexWrap:"wrap",marginBottom:18}}><div><div style={{fontSize:12,letterSpacing:3,color:"#6b7280",fontWeight:800}}>CROSS NODE MANAGEMENT</div><h1 style={{margin:"4px 0",fontSize:36}}>経営ダッシュボード</h1><p style={{margin:0,color:"#6b7280"}}>仕入・在庫・販売・利益・経理をひとつに。</p></div><div style={{display:"flex",gap:10}}><select value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} style={{padding:"11px 14px",borderRadius:10,border:"1px solid #d1d5db",background:"#fff"}}>{months.map(m=><option key={m}>{m}</option>)}</select><a href="/" style={{padding:"11px 15px",borderRadius:10,background:"#111827",color:"#fff",textDecoration:"none",fontWeight:700}}>← 管理画面</a></div></header>
  {msg&&<div style={{background:"#ecfdf5",border:"1px solid #bbf7d0",color:"#166534",padding:"12px 16px",borderRadius:10,marginBottom:16}}>{msg}</div>}
  <nav style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:8,marginBottom:18}}>{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{...btn,whiteSpace:"nowrap",background:tab===id?"#111827":"#fff",color:tab===id?"#fff":"#374151",border:tab===id?0:"1px solid #e5e7eb"}}>{label}</button>)}</nav>
  {tab==="overview"&&<><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(165px,1fr))",gap:12}}>{[["売上",salesTotal],["商品原価",costTotal],["送料",shipTotal],["粗利",gross],["経費",expenseTotal],["営業利益",operating],["仕入",purchaseTotal],["在庫金額",stockValue]].map(([l,v])=><div style={card} key={String(l)}><div style={{fontSize:13,color:"#6b7280"}}>{l}</div><b style={{display:"block",fontSize:25,marginTop:7,color:l==="粗利"||l==="営業利益"?(Number(v)>=0?"#15803d":"#dc2626"):"#111827"}}>{yen(Number(v))}</b></div>)}</section><section style={{...card,marginTop:18}}><h2 style={{marginTop:0}}>今月の経営状況</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14}}><div><b>粗利率</b><div style={{fontSize:28,marginTop:5}}>{salesTotal?(gross/salesTotal*100).toFixed(1):"0.0"}%</div></div><div><b>経費率</b><div style={{fontSize:28,marginTop:5}}>{salesTotal?(expenseTotal/salesTotal*100).toFixed(1):"0.0"}%</div></div><div><b>営業利益率</b><div style={{fontSize:28,marginTop:5}}>{salesTotal?(operating/salesTotal*100).toFixed(1):"0.0"}%</div></div><div><b>在庫</b><div style={{fontSize:28,marginTop:5}}>{stockUnits.toLocaleString()}個</div><div style={{color:"#6b7280"}}>{yen(stockValue)}</div></div></div></section></>}
  {tab==="products"&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:0}}>💰 商品別利益分析</h2><p style={{color:"#6b7280"}}>全期間の売上・原価・送料・粗利・利益率。</p></div><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="商品名・JAN・SKU・型番" style={{padding:"11px 14px",border:"1px solid #d1d5db",borderRadius:10,minWidth:280}}/></div>{table(["商品","販売数","売上","原価","送料","粗利","利益率","在庫"],productRows.slice(0,500).map(p=><tr key={p.id}>{[<div><b>{p.name}</b><div style={{fontSize:11,color:"#9ca3af"}}>{p.jan_code||""}</div></div>,p.qty,yen(p.sales),yen(p.cost),yen(p.ship),yen(p.profit),`${p.margin.toFixed(1)}%`,Number(p.stock_quantity||0)].map((v,i)=><td key={i} style={{padding:9,borderBottom:"1px solid #f1f5f9",textAlign:i===0?"left":"right",color:i===5?(p.profit>=0?"#15803d":"#dc2626"):"inherit",fontWeight:i===5?700:400}}>{v}</td>)}</tr>))}</section>}
  {tab==="channels"&&<section style={card}><h2 style={{marginTop:0}}>🛒 販売先別利益</h2>{table(["販売先","販売数","売上","原価","送料","粗利","利益率"],channelRows.map(r=><tr key={r.channel}>{[r.channel,r.qty,yen(r.sales),yen(r.cost),yen(r.ship),yen(r.profit),`${r.margin.toFixed(1)}%`].map((v,i)=><td key={i} style={{padding:9,borderBottom:"1px solid #f1f5f9",textAlign:i===0?"left":"right",fontWeight:i===5?700:400}}>{v}</td>)}</tr>))}</section>}
  {tab==="stock"&&<section style={card}><h2 style={{marginTop:0}}>📦 在庫金額・滞留分析</h2><p style={{color:"#6b7280"}}>警告を増やさず、必要な時だけ在庫の寝具合を確認できます。</p>{table(["商品","在庫","在庫金額","最終販売","経過日数","原価"],aging.slice(0,500).map(r=><tr key={r.p.id}><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}><b>{r.p.name}</b></td><td style={{padding:9,textAlign:"right"}}>{Number(r.p.stock_quantity||0)}</td><td style={{padding:9,textAlign:"right"}}>{yen(r.value)}</td><td style={{padding:9,textAlign:"right"}}>{r.last||"未販売"}</td><td style={{padding:9,textAlign:"right"}}>{r.days}日</td><td style={{padding:9,textAlign:"right"}}>{yen(r.p.cost_price)}</td></tr>))}</section>}
  {tab==="purchases"&&<section style={card}><h2 style={{marginTop:0}}>🧾 仕入・発注管理</h2><p style={{color:"#6b7280"}}>発注点は商品ごとの設定値を使用。ホーム画面には在庫不足警告を表示しません。</p>{table(["商品","現在庫","発注点","不足数","原価","在庫金額"],reorder.slice(0,500).map(p=>{const s=Number(p.stock_quantity||0),r=Number(p.reorder_point||0);return <tr key={p.id}><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}><b>{p.name}</b><div style={{fontSize:11,color:"#9ca3af"}}>{p.jan_code||""}</div></td><td style={{padding:9,textAlign:"right"}}>{s}</td><td style={{padding:9,textAlign:"right"}}>{r}</td><td style={{padding:9,textAlign:"right",fontWeight:700}}>{Math.max(r-s,0)}</td><td style={{padding:9,textAlign:"right"}}>{yen(p.cost_price)}</td><td style={{padding:9,textAlign:"right"}}>{yen(s*Number(p.cost_price||0))}</td></tr>}) )}</section>}
  {tab==="pl"&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10}}><div><h2 style={{margin:0}}>📊 月次・年次損益</h2><p style={{color:"#6b7280"}}>年間の売上・粗利・経費・営業利益・仕入を一覧化。</p></div><select value={year} onChange={e=>setSelectedMonth(`${e.target.value}-01`)} style={{padding:"10px 12px",border:"1px solid #d1d5db",borderRadius:10}}>{Array.from(new Set(months.map(yr))).sort().reverse().map(y=><option key={y}>{y}</option>)}</select></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12,marginTop:15}}>{[["年間売上",at.sales],["年間粗利",at.gross],["年間経費",at.expense],["年間営業利益",at.operating],["年間仕入",at.purchase]].map(([l,v])=><div key={String(l)} style={{background:"#f8fafc",borderRadius:12,padding:14}}><div style={{fontSize:12,color:"#6b7280"}}>{l}</div><b style={{fontSize:22}}>{yen(Number(v))}</b></div>)}</div>{table(["月","売上","原価","送料","粗利","経費","営業利益","仕入"],annual.map(r=><tr key={r.m}>{[r.m,yen(r.sales),yen(r.cost),yen(r.ship),yen(r.gross),yen(r.expense),yen(r.operating),yen(r.purchase)].map((v,i)=><td key={i} style={{padding:9,textAlign:i===0?"left":"right",borderBottom:"1px solid #f1f5f9",color:i===6?(r.operating>=0?"#15803d":"#dc2626"):"inherit",fontWeight:i===6?700:400}}>{v}</td>)}</tr>))}</section>}
  {tab==="cash"&&<section style={card}><h2 style={{marginTop:0}}>💴 簡易資金繰り</h2><p style={{color:"#6b7280"}}>入金・支払予定日を別管理していないため、売上−仕入−経費を簡易キャッシュフローとして表示します。</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{[["年間売上",at.sales],["年間仕入",at.purchase],["年間経費",at.expense],["年間簡易収支",at.cash]].map(([l,v])=><div key={String(l)} style={card}><div style={{color:"#6b7280"}}>{l}</div><b style={{fontSize:25,color:l==="年間簡易収支"?(Number(v)>=0?"#15803d":"#dc2626"):"#111827"}}>{yen(Number(v))}</b></div>)}</div>{table(["月","売上","仕入","経費","簡易収支"],annual.map(r=><tr key={r.m}>{[r.m,yen(r.sales),yen(r.purchase),yen(r.expense),yen(r.cash)].map((v,i)=><td key={i} style={{padding:9,textAlign:i===0?"left":"right",borderBottom:"1px solid #f1f5f9",color:i===4?(r.cash>=0?"#15803d":"#dc2626"):"inherit",fontWeight:i===4?700:400}}>{v}</td>)}</tr>))}</section>}
  {tab==="io"&&<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18}}><div style={card}><h2 style={{marginTop:0}}>📥 CSV一括登録・出力</h2><p style={{color:"#6b7280"}}>商品マスターをCSVから新規登録・JANで更新。</p><input ref={file} type="file" accept=".csv,text/csv" disabled={importing} onChange={importCsv}/><div style={{display:"flex",gap:8,marginTop:14,flexWrap:"wrap"}}><button style={{...btn,background:"#111827",color:"#fff"}} onClick={productsCsv}>商品CSV出力</button><button style={{...btn,background:"#eef2ff"}} onClick={ledgerCsv}>選択月の帳簿CSV</button></div><small style={{color:"#6b7280"}}>列：商品名 / JANコード / SKU / 型番 / ブランド / カテゴリ / 在庫数 / 発注点 / 原価 / 販売価格</small></div><div style={card}><h2 style={{marginTop:0}}>💾 バックアップ</h2><p style={{color:"#6b7280"}}>商品・売上・仕入・経費を1つのJSONに保存します。</p><button style={{...btn,background:"#111827",color:"#fff"}} onClick={backup}>JSONバックアップを作成</button><div style={{marginTop:12,color:"#6b7280",fontSize:13}}>商品 {products.length}件 / 売上 {sales.length}件 / 仕入 {purchases.length}件 / 経費 {expenses.length}件</div></div></section>}
 </div></main>;
}
